In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

In [ ]:
data_f=pd.read_csv('/content/1.01.+Simple+linear+regression.csv')
data_f.head()

SAT   GPA
0  1714  2.40
1  1664  2.52
2  1760  2.54
3  1685  2.74
4  1693  2.83

#Creating Regression

In [ ]:
x=data_f['SAT']
y=data_f['GPA']




changing dimension of the vector to 2 dimension matrix as scikit learn does not fancy 1D array 

In [ ]:
x_matrix=x.values.reshape(84,1)
x_matrix.shape

(84, 1)

In [ ]:
y_matrix=y.values.reshape(-1,1)
y_matrix.shape

(84, 1)

In [ ]:
reg=LinearRegression()
reg.fit(x_matrix,y)

LinearRegression()

R-squared

In [ ]:
reg.score(x_matrix,y)

0.40600391479679754

Coefficients

In [ ]:
reg.coef_

array([0.00165569])

Intercept

In [ ]:
reg.intercept_

0.2750402996602799

MAKING PREDICTION

In [ ]:
new_data=pd.DataFrame(data=[2000,1760],columns=['SAT'])
new_data

SAT
0  2000
1  1760

In [ ]:
reg.predict(new_data)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([3.5864164 , 3.18905127])

In [ ]:
new_data['Predicted GPA']=reg.predict(new_data)
new_data

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


SAT  Predicted GPA
0  2000       3.586416
1  1760       3.189051

#Multiple Linear Regression

In [ ]:
data=pd.read_csv('/content/1.02.+Multiple+linear+regression.csv')
data

SAT   GPA  Rand 1,2,3
0   1714  2.40           1
1   1664  2.52           3
2   1760  2.54           3
3   1685  2.74           3
4   1693  2.83           2
..   ...   ...         ...
79  1936  3.71           3
80  1810  3.71           1
81  1987  3.73           3
82  1962  3.76           1
83  2050  3.81           2

[84 rows x 3 columns]

In [ ]:
data.describe()

SAT        GPA  Rand 1,2,3
count    84.000000  84.000000   84.000000
mean   1845.273810   3.330238    2.059524
std     104.530661   0.271617    0.855192
min    1634.000000   2.400000    1.000000
25%    1772.000000   3.190000    1.000000
50%    1846.000000   3.380000    2.000000
75%    1934.000000   3.502500    3.000000
max    2050.000000   3.810000    3.000000

#Create Multiple Regression

In [ ]:
x=data[['SAT','Rand 1,2,3']]
y=data['GPA']

In [ ]:
reg=LinearRegression()
reg.fit(x,y)

LinearRegression()

In [ ]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [ ]:
reg.intercept_

0.29603261264909486

Calculating R-squared

In [ ]:
reg.score(x,y)

0.4066811952814283

###Formula for adjusted R^2

$R^2_(adj.) =1 - (1-R^2)*\frac{n-1}{n-p-1}$

n= number of observations

p=number of predictors

In [ ]:
x.shape

(84, 2)

In [ ]:
r2=reg.score(x,y)

n=x.shape[0]
p=x.shape[1]

adj_r2=1-(1-r2)*(n-1)/(n-p-1)
adj_r2

0.3920313482513401

##Feature Selection

In [ ]:
from sklearn.feature_selection import f_regression

In [ ]:
f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

1st array= F-statistics

2bd array= p-values

In [ ]:
p_values=f_regression(x,y)[1]
p_values

array([7.19951844e-11, 6.76291372e-01])

In [ ]:
p_values.round(4)

array([0.    , 0.6763])

Therefore.. SAT is a useful variable whereas

Rand 1,2,3 is a useless variable

##Creating a summary table

In [ ]:
reg_summary=pd.DataFrame(data=x.columns.values,columns=['Features'])
reg_summary

Features
0         SAT
1  Rand 1,2,3

In [ ]:
reg_summary['Coefficients']=reg.coef_
reg_summary['p-values']=p_values.round(3)

In [ ]:
reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676

#Standardization

In [ ]:
from sklearn.preprocessing import StandardScaler

In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(x)

StandardScaler()

In [ ]:
x_scaled=scaler.transform(x)

In [ ]:
x_scaled

array([[-1.26338288, -1.24637147],
       [-1.74458431,  1.10632974],
       [-0.82067757,  1.10632974],
       [-1.54247971,  1.10632974],
       [-1.46548748, -0.07002087],
       [-1.68684014, -1.24637147],
       [-0.78218146, -0.07002087],
       [-0.78218146, -1.24637147],
       [-0.51270866, -0.07002087],
       [ 0.04548499,  1.10632974],
       [-1.06127829,  1.10632974],
       [-0.67631715, -0.07002087],
       [-1.06127829, -1.24637147],
       [-1.28263094,  1.10632974],
       [-0.6955652 , -0.07002087],
       [ 0.25721362, -0.07002087],
       [-0.86879772,  1.10632974],
       [-1.64834403, -0.07002087],
       [-0.03150724,  1.10632974],
       [-0.57045283,  1.10632974],
       [-0.81105355,  1.10632974],
       [-1.18639066,  1.10632974],
       [-1.75420834,  1.10632974],
       [-1.52323165, -1.24637147],
       [ 1.23886453, -1.24637147],
       [-0.18549169, -1.24637147],
       [-0.5608288 , -1.24637147],
       [-0.23361183,  1.10632974],
       [ 1.68156984,

##Regression with scaled feature

In [ ]:
reg=LinearRegression()
reg.fit(x_scaled,y)

LinearRegression()

In [ ]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [ ]:
reg.intercept_

3.330238095238095

coefficients/feature=weights

intercept=bias


In [ ]:
reg_summary=pd.DataFrame([['Bias'],['SAT'],['Rand 1,2,3']],columns=['Features'])
reg_summary['Weights']=reg.intercept_,reg.coef_[0],reg.coef_[1]

In [ ]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030

##Making prediction with standardized coeffiients(weights)

In [ ]:
new_data=pd.DataFrame(data=[[1700,2],[1000,1]],columns=['SAT','Rand 1,2,3'])
new_data

SAT  Rand 1,2,3
0  1700           2
1  1000           1

In [ ]:
reg.predict(new_data)

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:432: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([295.39979563, 175.13710077])

In [ ]:
new_data_scaled=scaler.transform(new_data)
new_data_scaled

array([[-1.39811928, -0.07002087],
       [-8.13493924, -1.24637147]])

In [ ]:
new_data_scaled=scaler.transform(new_data)
reg.predict(new_data_scaled)

array([3.09051403, 1.94130459])

##**Removal of Rand 1,2,3**

In [ ]:
reg_simple=LinearRegression()

In [ ]:
y

In [ ]:
x_scaled.shape

(84, 2)

In [ ]:
x_simple_matrix=x_scaled[:,0].reshape(-1,1)
reg_simple.fit(x_simple_matrix,y)

LinearRegression()

In [ ]:
reg_simple.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.08970998, 1.93072835])