#Importing Libraries

In [ ]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split


#Generating Data for Splitting

In [ ]:
array_a=np.arange(1,101)
array_a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [ ]:
array_b=np.arange(301,401)
array_b

array([301, 302, 303, 304, 305, 306, 307, 308, 309, 310, 311, 312, 313,
       314, 315, 316, 317, 318, 319, 320, 321, 322, 323, 324, 325, 326,
       327, 328, 329, 330, 331, 332, 333, 334, 335, 336, 337, 338, 339,
       340, 341, 342, 343, 344, 345, 346, 347, 348, 349, 350, 351, 352,
       353, 354, 355, 356, 357, 358, 359, 360, 361, 362, 363, 364, 365,
       366, 367, 368, 369, 370, 371, 372, 373, 374, 375, 376, 377, 378,
       379, 380, 381, 382, 383, 384, 385, 386, 387, 388, 389, 390, 391,
       392, 393, 394, 395, 396, 397, 398, 399, 400])

#Split the Data

In [ ]:
array_a_train,array_a_test=train_test_split(array_a)

In [ ]:
array_a_train.shape,array_a_test.shape

((75,), (25,))

In [ ]:
array_a_train,array_a_test=train_test_split(array_a,test_size=0.2)

In [ ]:
array_a_train.shape,array_a_test.shape

((80,), (20,))

In [ ]:
array_a_train

array([89, 30,  4, 60, 91, 67, 66, 80, 13, 47, 86, 37, 92, 27, 65, 31, 99,
       98, 96, 59, 17, 94, 74, 49, 71, 54, 56, 61, 25, 35, 53, 72, 75, 58,
       68, 64, 23, 90, 62, 20, 97, 50, 48, 42, 87, 93, 45,  2, 77, 40, 38,
       84, 32, 51,  7, 95, 88, 14, 33, 83, 55, 15, 22, 79, 29, 12, 43,  9,
       78, 81, 44, 52, 82, 16, 21,  8, 34, 46, 57, 41])

In [ ]:
array_a_train,array_a_test=train_test_split(array_a,test_size=0.2,shuffle=False)
array_a_train

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80])

In [ ]:
array_a_train,array_a_test=train_test_split(array_a,test_size=0.2,random_state=42)
array_a_train

array([ 56,  89,  27,  43,  70,  16,  41,  97,  10,  73,  12,  48,  86,
        29,  94,   6,  67,  66,  36,  17,  50,  35,   8,  96,  28,  20,
        82,  26,  63,  14,  25,   4,  18,  39,   9,  79,   7,  65,  37,
        90,  57, 100,  55,  44,  51,  68,  47,  69,  62,  98,  80,  42,
        59,  49,  99,  58,  76,  33,  95,  60,  64,  85,  38,  30,   2,
        53,  22,   3,  24,  88,  92,  75,  87,  83,  21,  61,  72,  15,
        93,  52])

In [ ]:
array_a_train,array_a_test,b_train,b_test=train_test_split(array_a,array_b,test_size=0.2)

In [ ]:
b_train

array([321, 309, 323, 328, 350, 385, 384, 390, 349, 370, 348, 329, 376,
       308, 352, 336, 375, 320, 341, 363, 332, 340, 400, 388, 374, 315,
       368, 342, 369, 314, 316, 380, 354, 305, 306, 325, 312, 399, 335,
       396, 397, 381, 339, 331, 344, 346, 387, 343, 347, 386, 324, 338,
       337, 322, 382, 373, 361, 355, 319, 327, 366, 371, 302, 334, 360,
       310, 398, 383, 330, 357, 307, 393, 345, 317, 372, 359, 391, 303,
       333, 367])

In [ ]:
b_test

array([379, 326, 313, 364, 304, 311, 378, 389, 392, 318, 395, 365, 358,
       301, 394, 351, 362, 377, 356, 353])